/*
 * paper-loader-gen
 * Copyright (c) 2026 Harrison Boyd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package dev.hboyd.paperloadergen

import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.Dependency
import org.gradle.api.artifacts.repositories.MavenArtifactRepository
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.TaskAction
import java.io.FileWriter
import java.io.PrintWriter
import java.nio.file.Files
import java.nio.file.Path
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlin.time.Clock
import kotlin.time.toJavaInstant

/**
 * Task that generates the Paper Loader class.
 */
@CacheableTask
abstract class PaperLoaderGenTask : DefaultTask() {
    init {
        group = "generate"
    }

    /**
     * The fully qualified path to the generated Paper Loader class.
     */
    @get:Input
    abstract val classPath: Property<String>

    @get:Input
    abstract val repositories: ListProperty<MavenArtifactRepository>

    @get:Input
    abstract val dependencies: ListProperty<Dependency>

    @get:Input
    abstract val generatedOutputDir: Property<Path>

    /**
     * The fully qualified path to the generated Paper Loader class.
     */
    @get:Optional
    @get:Input
    abstract val additionalDependencies: SetProperty<String>

    @TaskAction
    fun generate() {
        val outputFile: Path = generatedOutputDir.get()
            .resolve(classPath.get().replace('.', '/') + ".java")

        Files.createDirectories(outputFile.parent)

        PrintWriter(FileWriter(outputFile.toFile())).use { writer ->
            writer.format(
                """
                    //
                    // DO NOT EDIT - File generated by the dev.hboyd.paperloadergen Gradle plugin.
                    //
                    
                    package %s;
                    
                    import io.papermc.paper.plugin.loader.PluginClasspathBuilder;
                    import io.papermc.paper.plugin.loader.PluginLoader;
                    import io.papermc.paper.plugin.loader.library.impl.MavenLibraryResolver;
                    import org.eclipse.aether.artifact.DefaultArtifact;
                    import org.eclipse.aether.graph.Dependency;
                    import org.eclipse.aether.repository.RemoteRepository;
                    import org.eclipse.aether.repository.LocalRepository;
                    import org.jspecify.annotations.NonNull;
                    import javax.annotation.processing.Generated;
                    
                    @Generated(value = "dev.hboyd.paperloadergen.PaperLoaderGenerationTask", date = "%s", comments = "Version: %s")
                    @SuppressWarnings({"UnstableApiUsage", "unused"})
                    public final class %s implements PluginLoader {
                        @Override
                        public void classloader(@NonNull PluginClasspathBuilder classpathBuilder) {
                            MavenLibraryResolver resolver = new MavenLibraryResolver();
                            resolver.addRepository(new RemoteRepository.Builder("maven-central", "default", MavenLibraryResolver.MAVEN_CENTRAL_DEFAULT_MIRROR).build());
                """.trimIndent(),
                classPath.get().substringBeforeLast('.'),
                DateTimeFormatter.ISO_OFFSET_DATE_TIME.withZone(ZoneId.of("UTC")).format(Clock.System.now().toJavaInstant()),
                PaperLoaderGen.pluginVersion(),
                classPath.get().substringAfterLast('.')
            )

            repositories.get().forEach {
                writer.format("\n        resolver.addRepository(new RemoteRepository.Builder(\"${it.name}\", \"default\", \"${it.url}\").build());")
            }

            writer.write("\n")

            dependencies.get().forEach {
                writer.format("\n        resolver.addDependency(new Dependency(new DefaultArtifact(\"${it.group}:${it.name}:${it.version}\"), null));")
            }

            additionalDependencies.get().forEach {
                writer.format("\n        resolver.addDependency(new Dependency(new DefaultArtifact(\"${it}\"), null));")
            }

            writer.write(
                """
                    
                    
                            classpathBuilder.addLibrary(resolver);
                        }
                    }
                """.trimIndent()
            )
        }
    }

}
